### ISSUE TITLE
X.X.X.X is currently unable to handle this request. HTTP ERROR 500

### ISSUE THREAD

**Issue by zakigates** [zakigates/HTTP-ERROR-500#1]
I'm asked to edit a cake php application code to adapt it to a certain need. To do so I followed this steps.

1. I logged in to my distant server.
2. I installed xampp.
3. Put the application in this location : /opt/lampp/htdocs/CarteInteractiveHoceima
4. I typed this url : http://51.254.205.243/CarteInteractiveHoceima/index.php

Although I got this error : **51.254.205.243 is currently unable to handle this request. HTTP ERROR 500**

I don't know what's going on. I did several researches. Some said that I have to set the .htaccess file this way:

`<IfModule mod_rewrite.c>
	RewriteEngine on
	# Uncomment if you have a .well-known directory in the root folder, e.g. for the Let's Encrypt challenge
    RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-l
    RewriteRule ^(.*)$ index.php?url=$1 [QSA,L]
</IfModule>`

Others said that I have to modify the httpd.conf file this way:

`Alias /bitnami/ "/opt/lampp/htdocs/"
Alias /bitnami "/opt/lampp/htdocs"
<Directory "/opt/lampp/htdocs">
    Options -Indexes
    AllowOverride All
    Order allow,deny
    Allow from all
</Directory>`

Others said that I should change the permissions `sudo chmod -R 777` to the folders: 

- app/tmp/cache

- app/tmp/cache/models

- app/tmp/cache/persistent

I tried all these stuff yet the page still don't load. I need you to help me solve this issue. It's been 3 days trying to fix this but in vain. 

Thanks

**Comment by zakigates** [comment]
I looked at error_log.php file and had this error : 

` [15-Oct-2018 09:41:02 Europe/Berlin] PHP Warning:  include(/Applications/MAMP/htdocs/CarteInteractive/lib/Cake/Error/ErrorHandler.php): failed to open stream: Aucun fichier ou dossier de ce type in /opt/lampp/htdocs/CarteInteractiveHoceima/lib/Cake/Core/App.php on line 547
[15-Oct-2018 09:41:02 Europe/Berlin] PHP Warning:  include(): Failed opening '/Applications/MAMP/htdocs/CarteInteractive/lib/Cake/Error/ErrorHandler.php' for inclusion (include_path='.:/opt/lampp/lib/php') in /opt/lampp/htdocs/CarteInteractiveHoceima/lib/Cake/Core/App.php on line 547
[15-Oct-2018 09:41:02 Europe/Berlin] PHP Warning:  set_error_handler() expects the argument (ErrorHandler::handleError) to be a valid callback in /opt/lampp/htdocs/CarteInteractiveHoceima/lib/Cake/Core/Configure.php on line 473
[15-Oct-2018 09:41:02 Europe/Berlin] PHP Warning:  include(/Applications/MAMP/htdocs/CarteInteractive/lib/Cake/Error/ErrorHandler.php): failed to open stream: Aucun fichier ou dossier de ce type in /opt/lampp/htdocs/CarteInteractiveHoceima/lib/Cake/Core/App.php on line 547
[15-Oct-2018 09:41:02 Europe/Berlin] PHP Warning:  include(): Failed opening '/Applications/MAMP/htdocs/CarteInteractive/lib/Cake/Error/ErrorHandler.php' for inclusion (include_path='.:/opt/lampp/lib/php') in /opt/lampp/htdocs/CarteInteractiveHoceima/lib/Cake/Core/App.php on line 547
[15-Oct-2018 09:41:02 Europe/Berlin] PHP Warning:  set_exception_handler() expects the argument (ErrorHandler::handleException) to be a valid callback in /opt/lampp/htdocs/CarteInteractiveHoceima/lib/Cake/Core/Configure.php on line 476
[15-Oct-2018 09:41:02 Europe/Berlin] PHP Warning:  include(/Applications/MAMP/htdocs/CarteInteractive/lib/Cake/Log/CakeLog.php): failed to open stream: Aucun fichier ou dossier de ce type in /opt/lampp/htdocs/CarteInteractiveHoceima/lib/Cake/Core/App.php on line 547
[15-Oct-2018 09:41:02 Europe/Berlin] PHP Warning:  include(): Failed opening '/Applications/MAMP/htdocs/CarteInteractive/lib/Cake/Log/CakeLog.php' for inclusion (include_path='.:/opt/lampp/lib/php') in /opt/lampp/htdocs/CarteInteractiveHoceima/lib/Cake/Core/App.php on line 547
[15-Oct-2018 09:41:02 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'CakeLog' not found in /opt/lampp/htdocs/CarteInteractiveHoceima/app/Config/bootstrap.php:102
Stack trace:
#0 /opt/lampp/htdocs/CarteInteractiveHoceima/lib/Cake/Core/Configure.php(98): include()
#1 /opt/lampp/htdocs/CarteInteractiveHoceima/lib/Cake/bootstrap.php(431): Configure::bootstrap(true)
#2 /opt/lampp/htdocs/CarteInteractiveHoceima/app/webroot/index.php(98): include('/opt/lampp/htdo...')
#3 /opt/lampp/htdocs/CarteInteractiveHoceima/index.php(41): require('/opt/lampp/htdo...')
#4 {main}
  thrown in /opt/lampp/htdocs/CarteInteractiveHoceima/app/Config/bootstrap.php on line 102
[15-Oct-2018 09:41:02 Europe/Berlin] PHP Warning:  include(/Applications/MAMP/htdocs/CarteInteractive/lib/Cake/Error/ErrorHandler.php): failed to open stream: Aucun fichier ou dossier de ce type in /opt/lampp/htdocs/CarteInteractiveHoceima/lib/Cake/Core/App.php on line 547
[15-Oct-2018 09:41:02 Europe/Berlin] PHP Warning:  include(): Failed opening '/Applications/MAMP/htdocs/CarteInteractive/lib/Cake/Error/ErrorHandler.php' for inclusion (include_path='.:/opt/lampp/lib/php') in /opt/lampp/htdocs/CarteInteractiveHoceima/lib/Cake/Core/App.php on line 547
[15-Oct-2018 09:41:02 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'ErrorHandler' not found in /opt/lampp/htdocs/CarteInteractiveHoceima/lib/Cake/Core/App.php:957
Stack trace:
#0 /opt/lampp/htdocs/CarteInteractiveHoceima/lib/Cake/Core/App.php(943): App::_checkFatalError()
#1 [internal function]: App::shutdown()
#2 {main}
  thrown in /opt/lampp/htdocs/CarteInteractiveHoceima/lib/Cake/Core/App.php on line 957`

I deleted the files in app/tmp/cache and now I'm getting this error : 

`Class 'Object' not found in /opt/lampp/htdocs/CarteInteractiveHoceima/lib/Cake/Controller/Controller.php` 

I need your help to solve this
